### ISSUE TITLE
Session time remaining is not displaying correct

### ISSUE THREAD

**Issue by 7upreturn** [yatt-ai/yattie#102]
# Bug Report

**Platform: Windows**

**YATTIE version: 0.10.0**

**Current behavior: During the session the time remaining limit will only show 00:00**

**Expected behavior: It should decrease from the amount of time that I input before starting the session**

**Steps to reproduce:**

1. Set a session and for the time limit input 59:00
2. Start the testing session 
3. Notice that the Elapsed time is increasing while Remaining  time will stay at 00:00:00

https://github.com/yatt-ai/yattie/assets/34812295/0327eb59-3a72-4b41-a87d-aaab35be417b

**Comment by isntlazy** [comment]
@dacoaster it works as expected on `main`: 
<img width="497" alt="image" src="https://github.com/yatt-ai/yattie/assets/23207978/20ce6d71-4a0f-45fb-be59-d57aadd13386">
issue can be closed I guess
