### ISSUE TITLE
bug: Previously Entered Values are Not Getting Cleared Even After Exiting the App With/Without Saving Session

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#103]
Platform: Windows,
YATTIE version:0.10.0

Current behavior: When we exit the application with or without saving the current session and relaunch the application, previously entered values for various fields like Title, Charter, Preconditions are still retained.

Expected behavior: 
1. Previously entered values for all the fields should be cleared everytime the application is re-launched. 
2. User should be always asked to save the session when exiting the application and should be given a warning the all the unsaved information will be lost.

Steps to reproduce:
1. Launch the application.
2. Click on Quick Start
3. Enter the field values in Title Charter , Pre Conditions, Notes etc.
4. Click on End Session & Save.
5. Either Click on Clear Session and Close the Application or Close the Application after Saving Session.
6. Re-launch the application
7. Previously entered values will still be displayed.

https://github.com/yatt-ai/yattie/assets/21246549/3740ec06-39a7-43fa-9e63-119278938c59

**Comment by dacoaster** [comment]
This will be addressed in #106.  Closing as a duplicate.

**Comment by dacoaster** [comment]
This will be addressed in #106.  Closing as a duplicate.

**Comment by dacoaster** [comment]
This will be addressed in #106.  Closing as a duplicate.
