### ISSUE TITLE
bug: Opening the Application after session save should open in Home screen

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#105]
Platform: Windows
YATTIE version: 0.10.0

Current behavior: 
1. When we re-open the Application after session save, Session Save screen is displayed instead of Home screen.
2. When we click on the Save button again, it gives a message "Do you ewant to save current progress" which misleading as previous session was already saved and no other progress is made.

Expected behavior: Since the previous session is already saved, relaunching the application should display the Home Page.

Steps to Replicate:
1. Click on Quick Test or New Exploratory session
2. Enter the required information.
3. Click on End Session & Save.
4. Click on Save Current Session icon.
5. Close the application.
6. Re-launch the application.
Issue: Application still displays Save Session Screen and clicking the save again displays the pop-up to save current progress again.

![image](https://github.com/yatt-ai/yattie/assets/21246549/fad43738-6cf2-438c-87e8-b7508dbf7177)

**Comment by dacoaster** [comment]
This will be addressed in #106 . Closing as a duplicate.
