### ISSUE TITLE
feat: Ask user if they'd like to resume last session

### ISSUE THREAD

**Issue by dacoaster** [yatt-ai/yattie#106]
Currently the app automatically resumes where you left off last.  This should be an option with a dialog prompting whether the user would like to resume or start fresh.

**Comment by isntlazy** [comment]
yes, just rechecked on `main` it looks like this:
<img width="1128" alt="image" src="https://github.com/yatt-ai/yattie/assets/23207978/d6da0de7-6aab-46b5-bd12-7920f542ff22">

**Comment by dacoaster** [comment]
@isntlazy - Can we change it to say the inverse "Do you want to continue your last session?"

**Comment by isntlazy** [comment]
> @isntlazy - Can we change it to say the inverse "Do you want to continue your last session?"

sure, will do that

**Comment by isntlazy** [comment]
@dacoaster created PR with this change
