### ISSUE TITLE
bug: Elapsed Time continues to increment even after we exit and re-launch the app

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#107]
Platform: Windows
YATTIE version: 0.10.0

Current behavior: Elapsed Time keeps incrementing even though when we exit the application and relaunch it.

Expected behavior: Elapsed Time should stop for the current session when application is closed or exited.

https://github.com/yatt-ai/yattie/assets/21246549/2c3a18c8-be52-4b1e-92bf-826240cf7d8a

**Comment by dacoaster** [comment]
This will be addressed in #106.  Closing as duplicate.
