### ISSUE TITLE
feat: show basic connection info in settings connections tab

### ISSUE THREAD

**Issue by dacoaster** [yatt-ai/yattie#126]
# Feature Request

Show basic info about various connections in settings tab and allow users to signout or remove connections there.

**Comment by dacoaster** [comment]
@dockabernathy01 - I'll leave this one for you.

**Comment by dockabernathy01** [comment]
Hi @dacoaster.
What do you think about this?
Please check and let me know.
![Connections Tab](https://github.com/yatt-ai/yattie/assets/146516559/f047bd13-761a-455c-b310-eb83811f4211)

**Comment by dacoaster** [comment]
@dockabernathy01 

This looks ok to me

Can you add a title under the logout icon?

**Comment by dockabernathy01** [comment]
@dacoaster , What do you think about this?
Like adding a tooltip.
![Connections Tab_1](https://github.com/yatt-ai/yattie/assets/146516559/d48adb08-1afb-46a3-b454-763772233068)

**Comment by dacoaster** [comment]
That's fine and we should add an open tooltip on the other icon.
