### ISSUE TITLE
feat: quicker download of report PDF

### ISSUE THREAD

**Issue by dacoaster** [yatt-ai/yattie#129]
# Feature Request

Rather than nesting the final report in a zip folder with all assets users should be able to download it directly

**Comment by dacoaster** [comment]
They should get the option whether to download the entire session archive or just the report

**Comment by dacoaster** [comment]
@dockabernathy01

**Comment by dockabernathy01** [comment]
@dacoaster , I have made the ui like this.
Please check and let me know.
Is it ok?
![pdf](https://github.com/yatt-ai/yattie/assets/146516559/acf15696-d189-4e20-99d8-9e28c55089af)
![pdf_1](https://github.com/yatt-ai/yattie/assets/146516559/296ca451-476f-453a-9b45-5c799126cc83)

**Comment by dacoaster** [comment]
@dockabernathy01 this is good
