### ISSUE TITLE
dev: remove unused views/components

### ISSUE THREAD

**Issue by dacoaster** [yatt-ai/yattie#148]
After moving to using dialogs for all popups, some views (and potentially components) will no longer ever be used.  (e.g. AddEvidence/EditEvidence)

**Comment by dockabernathy01** [comment]
@dacoaster , Should I  change the code to use popup instead of components?
For instance, currently NotesWrapper uses components. not Popup.

**Comment by dacoaster** [comment]
Please just leave the code functioning as is and remove views/components
that are no longer used

David Acosta • Senior Consultant
Rocksteady Technology
p. (413) 341-2430  e. ***@***.***
w. www.rocksteady.technology

**Comment by dockabernathy01** [comment]
Sure.
