### ISSUE TITLE
feat: Workspace should be full screen when maximizing the application

### ISSUE THREAD

**Issue by narkhedeshubham** [yatt-ai/yattie#33]
# Feature Request

**Describe the Feature Request**

When we maximize the application the workspace should be full screen, now it stays in the middle of the screen.

![screen size](https://user-images.githubusercontent.com/76529337/228435605-9b7ba4ce-274c-424a-92eb-6c6b86653bb8.png)

**Comment by devknight216** [comment]
I will start from this issue.
