### ISSUE TITLE
feat: Inclusion of Additional System Information in Environment Section of PDF Report.

### ISSUE THREAD

**Issue by narkhedeshubham** [yatt-ai/yattie#51]
# Feature Request

**Describe the Feature Request**

It would be helpful to have more information about the environment included in the PDF report generated.

**Describe Preferred Solution**

It would be useful to include additional information from the DXDiag tool, which can provide a comprehensive report of the system's hardware and software configuration.

![image](https://github.com/dacoaster/yattie/assets/76529337/f3f6bd59-e381-4edc-b07e-c93bd8eb1456)

![image](https://github.com/dacoaster/yattie/assets/76529337/49b886ea-3626-453d-abb4-01168f77c49d)

**Comment by dacoaster** [comment]
@devknight216
