### ISSUE TITLE
feat: Option to Add Organization Logo in PDF Generated Report

### ISSUE THREAD

**Issue by narkhedeshubham** [yatt-ai/yattie#52]
# Feature Request

**Describe the Feature Request**

It would be beneficial to have the option to add their own organization symbol in the PDF-generated report. 

![image](https://github.com/dacoaster/yattie/assets/76529337/66d94e9d-a03a-4937-8016-33dc75dd9167)

**Comment by dacoaster** [comment]
@dockabernathy01 - I'll leave this one for you.
