### ISSUE TITLE
feat: Add a setting for cached session clean up

### ISSUE THREAD

**Issue by dacoaster** [yatt-ai/yattie#71]
- Create a setting for retention days on cached sessions in the `${config}/sessions` folder
- Also add a "clear cache" button on the settings GeneralTab
- Set up a sane default in config also set on the settings GeneralTab
- Add a cleanup step in initialization that clears caches older than the retention setting

**Comment by dacoaster** [comment]
Currently all sessions get a folder with related evidence/files inside.  Over time this could consume a lot of disk space after many sessions.

**Comment by dacoaster** [comment]
@dockabernathy01

**Comment by dacoaster** [comment]
@dockabernathy01 - I'll leave this one for you.

**Comment by dockabernathy01** [comment]
@dacoaster, please tell me more about this issue.
Place a "Clear Cache" button to clear the sessions folder.
And if a session has been modified for more than 3 days(retention days), the session folder is automatically deleted.
Is it right?

**Comment by dockabernathy01** [comment]
![clear cache](https://github.com/yatt-ai/yattie/assets/146516559/11edb30e-8489-4474-a904-640c63b5d408)
![clear cache 1](https://github.com/yatt-ai/yattie/assets/146516559/9fe4c33a-3493-4dc4-ab8b-dd68076a2995)

**Comment by dacoaster** [comment]
Yes

please make the default retention period 7 days and change the wording to "Are you sure you want to clear the local session cache?"

**Comment by dockabernathy01** [comment]
Currently I store retention days like this.
config: {
   .....
   retentionDays: 7,
}
I think there is no need to make cache object and store retentionDays to cache object.

**Comment by dacoaster** [comment]
In the future we will likely add more options for managing the cache, so I'd like the key there for now

**Comment by dockabernathy01** [comment]
Ok, I got it.
And please check this video.
https://github.com/yatt-ai/yattie/assets/146516559/f2c3ab9e-f3ad-4da6-8a63-8e9beb0968bd
