### ISSUE TITLE
support: How to use the AI assistant

### ISSUE THREAD

**Issue by narkhedeshubham** [yatt-ai/yattie#88]
I was trying to use the AI assistant by importing my OpenAI Key in the application from settings. 

But I get this error,

![image](https://github.com/yatt-ai/yattie/assets/76529337/44074e22-bdec-42da-8183-095fb3daf720)

Can you please assist me on this.

**Comment by dacoaster** [comment]
@narkhedeshubham - a 429 is returned by an API when usage is being rare limited (too many requests). Please see [OpenAI’s documentation](https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests) on the issue.

Let me know if that doesn’t make sense or you think there is another issue.
