### ISSUE TITLE
bug: App opening throws an error on Windows 11 after installation

### ISSUE THREAD

**Issue by 7upreturn** [yatt-ai/yattie#92]
# Bug Report

**Platform: Windows 11 [Version 10.0.22621.2715]**

**YATTIE version: 0.8.0**

**Current behavior:**

I tried installing the Yattie application. 1st attempt was done using the default path of install from the installer. 2nd attempt was done in C:\ProgramFiles\Yattie 
In both cases, when trying to open the application a Javascript error is showing. I observed that after the install I have 3 Yattie processes running in the Task Manager which cannot be closed. It requires me to restart the computer.  
Tried to open both regular and with Run as administrator

**Expected behavior:**

After installation I can open the application with no errors showing.

**Steps to reproduce:**

1. Download Yattie 0.8.0 .exe file 
2. Install the application on Window 11 
3. Tried to open the application

**Related code:**
Task manager processes
![image](https://github.com/yatt-ai/yattie/assets/34812295/026b1ac1-3401-4cff-a6d5-d2d3e45e2152) 

Javascript error
![image](https://github.com/yatt-ai/yattie/assets/34812295/d7dc2a88-70f0-49fa-a26e-c941353e29b4)

**Other information:**

**Comment by constDave** [comment]
@7upreturn Thank you for reporting this! Please uninstall the app completely, remove the user data files, and install the latest version (0.10.0) - https://github.com/yatt-ai/yattie/releases 

Please let us know if those steps resolve the issue or if you continue to have issues.

**Comment by 7upreturn** [comment]
Thank you @dacoaster , @constDave 0.10.0 is working for me.

**Comment by dacoaster** [comment]
I removed the files for v0.8.0 since it has this bug on Windows.  Thank you for your report @7upreturn !
