### ISSUE TITLE
bug: Formatting of Survey Page is not proper

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#94]
# Bug Report

Platform: Windows
YATTIE version: 0.10.0

Current behavior: When we scroll up or down the https://yatt.ai/yattie-survey/ page, the content of the page overlaps with top navigation bar in blue

Expected behavior: Page content shouldn't overlap with the header. 

Steps to replicate:
1. Launch the application.
2. Click on File Menu option and select 'Take the YATTIE Survey' option.
3. Scroll down the page usinig the scroll bar.

![YattieSurveyIssue](https://github.com/yatt-ai/yattie/assets/21246549/a275fe66-7a44-4a74-bb6e-d4f9888a17f2)

**Comment by isntlazy** [comment]
I guess it was fixed at some point, looks great for me 
<img width="1390" alt="image" src="https://github.com/yatt-ai/yattie/assets/23207978/ee4b676e-32b9-4797-88c9-e664a2bbc5ef">
@dacoaster please close it if not actual

**Comment by dacoaster** [comment]
@isntlazy - This only happens when you scroll down.  I'll assign this bug to myself.
