### ISSUE TITLE
bug: Application hangs when we close Login to Jira browser.

### ISSUE THREAD

**Issue by afrozshaheenkhan** [yatt-ai/yattie#96]
# Bug Report

Platform: Windows
YATTIE version: 0.10.0

Current behavior: 
1. Application hangs when we click on login with jira Cloud option and close the browser without logging.
2. Back button doesn't work in the 'Sign in with Jira' screen to go back to Home screen.
3. When application is re-launched, we are taken to 'Sign in with Jira' and not home page.

Expected behavior: 
1. All the options should be displayed in 'Sign in with Jira' screen even when we close the browser without logging. 
2. Back button should be functional to go back to home page.
3. Everytime we launch the application, we should be taken to home screen first.

Steps to reproduce:
1. Launch the application.
2. Click on the Quick Test.
3. Click on User icon.
4. Click Login.
5. Click Sign in with JIRA
6. Click Login with JIRA cloud
7. Close the opened browser
8. Come back to Sign in with JIRA screen.

https://github.com/yatt-ai/yattie/assets/21246549/884101fa-1090-45ea-a538-ba604e502975

**Comment by isntlazy** [comment]
@dacoaster I see that logic of attempts to connect is already there, I went with leaving it as is but now it looks more user-friendly and clear for user, also fixed app restart as suggested
<img width="1107" alt="image" src="https://github.com/yatt-ai/yattie/assets/23207978/59599805-89c5-4e64-b644-8ef7d2cf2ce2">
